BUDGET_CATEGORIES = [
            "Salary/Wages",
            "Side Hustles",
            "Mortgage/Rent",
            "Utilities (Electricity, Water, Gas, Internet)",
            "Insurance (Health, Life, Car, Home)",
            "Debt Payments (Student Loans, Credit Cards)",
            "Subscriptions (Streaming Services, Gym Memberships)",
            "Groceries",
            "Dining Out",
            "Gas Station/Vending Machine",
            "Coffee Shops",
            "Transportation (Gas, Maintenance, Public Transport)",
            "Personal Care (Haircuts, Skincare)",
            "Household Supplies",
            "Medical Expenses (Co-pays, Prescriptions)",
            "Emergency Fund",
            "Retirement (401(k), IRA)",
            "Investment Accounts",
            "College Fund (for kids or personal)",
            "Big Purchases (House, Car, Vacation)",
            "Entertainment (Movies, Concerts, Hobbies)",
            "Travel",
            "Clothing",
            "Gifts & Donations",
            "Fitness & Health (Yoga Classes, Sports)",
            "Pet Care (Food, Vet Visits)",
            "Childcare/Education",
            "Home Improvement",
            "Professional Development (Courses, Certifications)"
        ]